<a href="https://colab.research.google.com/github/J-Sowmya-18/Deep-Learning-lab/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# Scalar_ex
scalar = np.array(5)
print("Scalar value:", scalar)

Scalar value: 5


In [3]:
# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)

Vector values: [1 2 3]


In [4]:
import numpy as np
#scalar_ex
scalar=np.array(5)
print("Scalar value:",scalar)
#vector ex
vector=np.array([1,2,3])
print("Vector values:",vector)
#2d tensor ex
matrix=np.array([[1,2,3],[4,5,6]])
print("2d tensor (matrix):\n",matrix)
#3d tensor_ex
tensor_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("3d tensor:\n",tensor_3d)
#4d tensor_es
tensor_4d=np.random.rand(2,3,4,5)
print("Shape of 4d tensor:",tensor_4d.shape)


Scalar value: 5
Vector values: [1 2 3]
2d tensor (matrix):
 [[1 2 3]
 [4 5 6]]
3d tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4d tensor: (2, 3, 4, 5)


In [5]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer
# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')
# Step 4: Train the Model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.2)
# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/5
100/100 [==============================] - 1s 5ms/step - loss: 8425.9854 - val_loss: 4926.4219
Epoch 2/5
100/100 [==============================] - 0s 4ms/step - loss: 2153.0522 - val_loss: 388.7645
Epoch 3/5
100/100 [==============================] - 0s 3ms/step - loss: 187.5041 - val_loss: 100.2128
Epoch 4/5
100/100 [==============================] - 0s 4ms/step - loss: 71.6242 - val_loss: 43.8374
Epoch 5/5
63/63 [==============================] - 0s 2ms/step - loss: 21.6979
Test Loss: 21.697925567626953
1/1 [==============================] - 0s 123ms/step
Predicted Sum: 65.37844848632812


In [8]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden
model.add(Dense(1))  # Output
# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')
# Step 4: Train the Model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.3)
# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
# Make a prediction
sample_input = np.array([[23, 45]])  # Ex_input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/5
77/77 [==============================] - 2s 9ms/step - loss: 9505.7334 - val_loss: 6443.7144
Epoch 2/5
77/77 [==============================] - 0s 3ms/step - loss: 4164.2866 - val_loss: 2104.0481
Epoch 3/5
77/77 [==============================] - 0s 3ms/step - loss: 1188.1875 - val_loss: 566.2463
Epoch 4/5
77/77 [==============================] - 0s 3ms/step - loss: 384.7094 - val_loss: 223.2211
Epoch 5/5
94/94 [==============================] - 0s 1ms/step - loss: 100.8571
Test Loss: 100.85706329345703
1/1 [==============================] - 0s 64ms/step
Predicted Sum: 64.7323989868164


In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden
model.add(Dense(1))  # Output
# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')
# Step 4: Train the Model
model.fit(X_train, y_train, epochs=10, batch_size=64, validation_split=0.3)
# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/10
77/77 [==============================] - 2s 8ms/step - loss: 8243.5273 - val_loss: 5634.8667
Epoch 2/10
77/77 [==============================] - 0s 6ms/step - loss: 2979.8909 - val_loss: 781.8811
Epoch 3/10
77/77 [==============================] - 0s 6ms/step - loss: 222.1254 - val_loss: 18.9047
Epoch 4/10
77/77 [==============================] - 0s 6ms/step - loss: 11.1421 - val_loss: 7.1572
Epoch 5/10
77/77 [==============================] - 1s 10ms/step - loss: 5.3616 - val_loss: 3.7712
Epoch 6/10
77/77 [==============================] - 0s 3ms/step - loss: 2.9881 - val_loss: 2.2946
Epoch 7/10
77/77 [==============================] - 0s 3ms/step - loss: 1.9473 - val_loss: 1.6329
Epoch 8/10
77/77 [==============================] - 0s 3ms/step - loss: 1.4671 - val_loss: 1.3107
Epoch 9/10
77/77 [==============================] - 0s 3ms/step - loss: 1.2114 - val_loss: 1.1200
Epoch 10/10
94/94 [==============================] - 0s 2ms/step - loss: 1.0074
Test Loss: 1.007351517

In [10]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=7, batch_size=64, validation_split=0.3)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/7
77/77 [==============================] - 1s 5ms/step - loss: 1463.6589 - val_loss: 341.5959
Epoch 2/7
77/77 [==============================] - 0s 3ms/step - loss: 85.3803 - val_loss: 12.2491
Epoch 3/7
77/77 [==============================] - 0s 3ms/step - loss: 7.7799 - val_loss: 5.5074
Epoch 4/7
77/77 [==============================] - 0s 3ms/step - loss: 3.8294 - val_loss: 2.9510
Epoch 5/7
77/77 [==============================] - 0s 3ms/step - loss: 2.1626 - val_loss: 1.6712
Epoch 6/7
77/77 [==============================] - 0s 3ms/step - loss: 1.2621 - val_loss: 0.9790
Epoch 7/7
94/94 [==============================] - 0s 2ms/step - loss: 0.5931
Test Loss: 0.5931494235992432


1/1 [==============================] - 0s 71ms/step
Predicted Sum: 68.25399780273438


In [13]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer
# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')
# Step 4: Train the Model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.3)
# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
# Make a prediction
sample_input = np.array([[10, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/5
77/77 [==============================] - 1s 4ms/step - loss: 5865.6875 - val_loss: 3780.1428
Epoch 2/5
77/77 [==============================] - 0s 3ms/step - loss: 1866.7888 - val_loss: 451.6869
Epoch 3/5
77/77 [==============================] - 0s 3ms/step - loss: 131.6298 - val_loss: 38.3747
Epoch 4/5
77/77 [==============================] - 0s 3ms/step - loss: 26.1040 - val_loss: 20.4630
Epoch 5/5
94/94 [==============================] - 0s 1ms/step - loss: 13.8619
Test Loss: 13.861869812011719
1/1 [==============================] - 0s 92ms/step
Predicted Sum: 56.651649475097656


In [18]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden
model.add(Dense(1))  # Output
# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')
# Step 4: Train the Model
model.fit(X_train, y_train, epochs=8, batch_size=64, validation_split=0.3)
# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
# Make a prediction
sample_input = np.array([[20, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/8
77/77 [==============================] - 1s 5ms/step - loss: 13875.7275 - val_loss: 12779.6035
Epoch 2/8
77/77 [==============================] - 0s 3ms/step - loss: 11626.8438 - val_loss: 9544.6709
Epoch 3/8
77/77 [==============================] - 0s 3ms/step - loss: 6322.1562 - val_loss: 2798.4507
Epoch 4/8
77/77 [==============================] - 0s 3ms/step - loss: 929.4500 - val_loss: 26.1064
Epoch 5/8
77/77 [==============================] - 0s 4ms/step - loss: 19.1112 - val_loss: 13.9600
Epoch 6/8
77/77 [==============================] - 0s 3ms/step - loss: 12.5308 - val_loss: 10.7529
Epoch 7/8
77/77 [==============================] - 0s 3ms/step - loss: 9.9115 - val_loss: 8.6942
Epoch 8/8
94/94 [==============================] - 0s 2ms/step - loss: 7.8361
Test Loss: 7.8360514640808105
1/1 [==============================] - 0s 75ms/step
Predicted Sum: 65.97876739501953


In [20]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer
# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')
# Step 4: Train the Model
model.fit(X_train, y_train, epochs=10, batch_size=64, validation_split=0.3)
# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
# Make a prediction
sample_input = np.array([[10, 15]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/10
77/77 [==============================] - 1s 5ms/step - loss: 6650.6953 - val_loss: 4261.3115
Epoch 2/10
77/77 [==============================] - 0s 3ms/step - loss: 2373.9077 - val_loss: 1011.4827
Epoch 3/10
77/77 [==============================] - 0s 3ms/step - loss: 551.7926 - val_loss: 357.0482
Epoch 4/10
77/77 [==============================] - 0s 3ms/step - loss: 281.2703 - val_loss: 227.9698
Epoch 5/10
77/77 [==============================] - 0s 3ms/step - loss: 154.8137 - val_loss: 93.5593
Epoch 6/10
77/77 [==============================] - 0s 3ms/step - loss: 54.4334 - val_loss: 31.3629
Epoch 7/10
77/77 [==============================] - 0s 3ms/step - loss: 20.4925 - val_loss: 13.8598
Epoch 8/10
77/77 [==============================] - 0s 3ms/step - loss: 9.8823 - val_loss: 7.1311
Epoch 9/10
77/77 [==============================] - 0s 3ms/step - loss: 5.3319 - val_loss: 4.1205
Epoch 10/10
94/94 [==============================] - 0s 2ms/step - loss: 2.3692
Test Loss: 

In [21]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer
# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')
# Step 4: Train the Model
model.fit(X_train, y_train, epochs=12, batch_size=32, validation_split=0.3)
# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/12
154/154 [==============================] - 1s 4ms/step - loss: 3086.4956 - val_loss: 1242.3594
Epoch 2/12
154/154 [==============================] - 0s 3ms/step - loss: 658.6569 - val_loss: 229.9999
Epoch 3/12
154/154 [==============================] - 0s 3ms/step - loss: 97.1566 - val_loss: 25.1538
Epoch 4/12
154/154 [==============================] - 0s 2ms/step - loss: 14.9750 - val_loss: 8.3647
Epoch 5/12
154/154 [==============================] - 1s 3ms/step - loss: 7.4616 - val_loss: 5.8615
Epoch 6/12
154/154 [==============================] - 0s 3ms/step - loss: 5.7191 - val_loss: 5.1582
Epoch 7/12
154/154 [==============================] - 1s 4ms/step - loss: 4.9847 - val_loss: 4.7000
Epoch 8/12
154/154 [==============================] - 0s 3ms/step - loss: 4.4786 - val_loss: 4.2281
Epoch 9/12
154/154 [==============================] - 1s 4ms/step - loss: 4.0203 - val_loss: 3.8404
Epoch 10/12
154/154 [==============================] - 1s 5ms/step - loss: 3.6132 - val

In [22]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden
model.add(Dense(1))  # Output
# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')
# Step 4: Train the Model
model.fit(X_train, y_train, epochs=15, batch_size=64, validation_split=0.2)
# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')
# Make a prediction
sample_input = np.array([[20, 40]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')

Epoch 1/15
88/88 [==============================] - 1s 6ms/step - loss: 10216.3604 - val_loss: 8362.6016
Epoch 2/15
88/88 [==============================] - 0s 3ms/step - loss: 4949.2905 - val_loss: 1224.7729
Epoch 3/15
88/88 [==============================] - 0s 3ms/step - loss: 366.5815 - val_loss: 120.6791
Epoch 4/15
88/88 [==============================] - 0s 3ms/step - loss: 65.6812 - val_loss: 36.5249
Epoch 5/15
88/88 [==============================] - 0s 3ms/step - loss: 24.6211 - val_loss: 19.2012
Epoch 6/15
88/88 [==============================] - 0s 3ms/step - loss: 15.8653 - val_loss: 14.3428
Epoch 7/15
88/88 [==============================] - 0s 3ms/step - loss: 12.5394 - val_loss: 11.8500
Epoch 8/15
88/88 [==============================] - 0s 3ms/step - loss: 10.4820 - val_loss: 10.0984
Epoch 9/15
88/88 [==============================] - 0s 3ms/step - loss: 8.9929 - val_loss: 8.8152
Epoch 10/15
88/88 [==============================] - 0s 3ms/step - loss: 7.8648 - val_loss: